### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Elastix'

### ISSUE THREAD

**Issue by duancaohui** [SuperElastix/SimpleElastix#103] opened 2017-06-15 03:48 UTC
my system is Ubuntu 16.04, 16GB RAM . 
I follow the steps in SuperBuild On Linux
$git clone https://github.com/kaspermarstal/SimpleElastix
$ mkdir build
$ cd build
$ cmake ../SimpleElastix/SuperBuild
$ make -j4

and Finally 
$ sudo python setup.py install
all successful!

In my  python 3.5 dist-packages, there are  SimpelTK and SimpleElastix (1.0.0rc1.dev554+gd6eaa)
but when I use sitk.Elastix or sitk.SimpleElastix, or import SimpleElastix, there are all none this module

why?

thank you

**Comment by PertuyF** [comment] 2017-06-15 21:31
Hi @duancaohui 

Did you tried this?
```Python
import SimpleITK as sitk

selx = sitk.ElastixImageFilter()
```

There was a renaming in [last release](https://github.com/SuperElastix/SimpleElastix/releases).
Some issues ([here](https://github.com/SuperElastix/SimpleElastix/issues/99), and [there](url)) already address this.

**Comment by varghesealex90** [comment] 2017-09-02 04:08
Hi ;

I am having the same issue, 
tried this piece
import SimpleITK as sitk
elastixImageFilter = sitk.ElastixImageFilter()
error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'ElastixImageFilter'


Please help

**Comment by kaspermarstal** [comment] 2017-09-02 10:29
Hi @varghesealex90, most likely you are importing an existing version of SimpleITK, and not SimpleElastix. Have you run `python setup.py install` in the `Wrapping/Python/Packaging` directory in the build tree?

**Comment by varghesealex90** [comment] 2017-09-11 08:19
Hi;
In that case, how do I fix this issue.

**Comment by varghesealex90** [comment] 2017-09-11 08:20
These are steps I did
$ git clone https://github.com/SuperElastix/SimpleElastix
$ mkdir build
$ cd build
$ cmake ../SimpleElastix/SuperBuild
$ make -j4
$ cd /SimpleITK-build/Wrapping/Python/Packaging
$ sudo python setup.py install

**Comment by kaspermarstal** [comment] 2017-09-11 09:32
You are doing it right. Perhaps SimpleElastix is installed for another interpreter than you are using for your code? Do you use a virtual environment? In that case you should activate it before running `sudo python setup.py install`. Forgive me if you already know this, it is hard to debug problems like this remotely.

**Comment by varghesealex90** [comment] 2017-09-11 09:45
I havent set any virtual environment, but I assume i did install simpleitk previously and this is what is creating the issue. I will try using python setup.py install

**Comment by anewlearner** [comment] 2017-09-22 14:14
@varghesealex90 Did you solved the problem now?
I installed the SimpleElastix successfully, but one day, it just did not work. So I installed it again, but it does not work.

**Comment by varghesealex90** [comment] 2017-09-22 14:26
Yes. I fixed it by uninstalling Simpleelsatix and SimpleITK and then
installing SimpleElastix from scratch

**Comment by kaspermarstal** [comment] 2017-09-24 17:50
Great! Closing :)

**Comment by anewlearner** [comment] 2017-09-27 03:26
@varghesealex90 Thanks for your answer.  I uninstalled the SimpleITK by "pip uninstall SimpleITK". Then I reinstalled the SimpleITK whel and reinstalled the SimpleElastix. But I can only import SimpleITK, but can not use any thing related to SimpleElastix. Is there anything wrong?

**Comment by varghesealex90** [comment] 2017-09-27 04:13
just to make sure could you remove simpleitk using "sudo"
Steps taken 
1) Remove simpleitk , using sudo pip uninstall
2) Reinstall SimpleElastix. No attempt made to reinstall SimpleITK because I believe SimpleElastix already has an inbuilt SimpleITK

**Comment by kaspermarstal** [comment] 2017-10-29 16:20
Closing. Seems to be resolved. Thanks everybody.

**Comment by anewlearner** [comment] 2017-10-31 07:01
SimpleElastix  can not work **again** :(. This is the second time, It is very strange. I just did not use it for several days. SimpleITK is ok. 
At this time, when I used 'pip uninstall', it said there was no simpleITK. So I manually deleted all files related to SimpleElastix, including some files under dist-package of python, 'build' folder and 'SimpleElastix' folder created before. Then I reinstall SimpleElastix. But it still can not work.
I am quite sure the step to install SimpleElastix is correct, because I successfully installed it for several times before.

**Comment by kaspermarstal** [comment] 2017-10-31 10:39
If pip install cannot find SimpleITK, but the files are there, then pip is most likely pointing to an environment different from what you think. Installing/uninstalling the python package into wrong directories is not something that we can fix on our side. However, you are welcome to open a new issue and describe exactly what commands you use and we can see if we can reproduce it.

**Comment by anewlearner** [comment] 2017-10-31 11:06
@kaspermarstal I finally fixed it. I thought there was something wrong with the installation. But it is not. Actually, it is related to the change of the function name. The `SimpleElastix` changed to `ElastixImageFilter`. But in the readme.md file and the document, it is still `SimpleElastix`. I followed the example there and can not find this function, so I wrongly thought I did not install it successfully.  

Although the problem is solved, there is still something strange. The function name has changed before I  my first of SimpleElastix. But I can use the older function name some time. This is why I thought it worked some time but seems to have some thing wrong later(It happened several times for me ).
Maybe it can do some help to the new users if you update the document and the readme.md.

Thanks for sharing such good codes. It really helps my work.

**Comment by daikankan** [comment] 2018-04-20 03:56
@kaspermarstal  Thanks for your work, this is a problem of installtion. I use a virtual environment, after activate it and running sudo python setup.py install, SimpleElastix still install to /usr/bin/python2.7 interpreter by default, not the interpreter of the virtual environment, do you have any idea of this problem ?

**Comment by PertuyF** [comment] 2018-04-21 10:42
@daikankan , `sudo` is usually a bad idea with virtual environments...
It seems that using `chmod` or `chown` on the environment could fix  the `python setup.py install` (see [here](https://stackoverflow.com/questions/2658902/in-my-virtualenv-i-need-to-use-sudo-for-all-commands?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), and [there](https://emilkirkegaard.dk/en/?p=5770)).

**Closed** 2018-09-12 09:43 UTC
