### ISSUE TITLE
How to  apply the transformation of groupwise registration on images and their corresponding label files?

### ISSUE THREAD

**Issue by sara-eb** [SuperElastix/SimpleElastix#255] opened 2018-12-17 12:56 UTC
Hi everyone, 
I am facing an issue in applying groupwise transformation on images.
I have two sets of images (baseline and follow-up scans (i.e., after 12 months)) and their corresponding segmentations. I have some doubts in correct understanding of applying transformation on these two sets of images. 

```
import SimpleITK as sitk
import numpy as np
import sys
from os import listdir
import os
import matplotlib.pyplot as plt
#concatenate the ND image into one (N+1)D images
image_dir='/home/es/workspace/registration/images/'
population=listdir(image_dir)
vectorOfImages=sitk.VectorOfImage()

for filename in population:
    vectorOfImages.push_back(sitk.ReadImage(image_dir+filename))
image=sitk.JoinSeries(vectorOfImages)

# Register
elastixImageFilter=sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(image)
elastixImageFilter.SetMovingImage(image)
elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap('groupwise'))
resultImage=elastixImageFilter.Execute()
print("done")
# saving the temple file obtained from the population
sitk.WriteImage(resultImage,image_dir+"template_population.nii.gz")
```

Once I am trying to apply the transformation in one of the images, I am facing an error:
```
resultImage = elastixImageFilter.GetResultImage()
transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()
newImage='/home/es/workspace/registration/images/image-9007827.nii.gz'#image_dir+filename
transformedNewImage = sitk.Transformix(newImage, transformParameterMapVector)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-25-a83bf5bd903b> in <module>()
      2 transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()
      3 newImage=image_dir+filename
----> 4 transformedNewImage = sitk.Transformix(newImage, transformParameterMapVector)
      5 #sitk.WriteImage(transformedNewImage = sitk.Transformix(newImage, transformParameterMapVector))

/home/esomayeh/softwares/SimpleElastix/build/SimpleITK-build/Wrapping/Python/SimpleITK.pyc in Transformix(*args)
  10739     Transformix(Image movingImage, VectorOfParameterMap parameterMapVector, bool const logToConsole=False, std::string const outputDirectory) -> Image
  10740     """
> 10741     return _SimpleITK.Transformix(*args)
  10742 class ImageRegistrationMethod(ProcessObject):
  10743     """

NotImplementedError: Wrong number or type of arguments for overloaded function 'Transformix'.
  Possible C/C++ prototypes are:
    itk::simple::Transformix(itk::simple::Image const &,std::map< std::string,std::vector< std::string,std::allocator< std::string > >,std::less< std::string >,std::allocator< std::pair< std::string const,std::vector< std::string,std::allocator< std::string > > > > > const,bool const,std::string const)
    itk::simple::Transformix(itk::simple::Image const &,std::vector< std::map< std::string,std::vector< std::string,std::allocator< std::string > >,std::less< std::string >,std::allocator< std::pair< std::string const,std::vector< std::string,std::allocator< std::string > > > > >,std::allocator< std::map< std::string,std::vector< std::string,std::allocator< std::string > >,std::less< std::string >,std::allocator< std::pair< std::string const,std::vector< std::string,std::allocator< std::string > > > > > > > const,bool const,std::string const)
```
My questions are as follows:

1. How to apply the transformation on all the images? 

2. Should we do the same transformation obtained from the `population` apply on label images (for example if we have saved the labels in a list `population_label=['label-001.nii.gz', 'label-002.nii.gz', ...]`)?

3. What about the followup scans? should we apply the transformation obtained for the baseline scans on these scans?

Your help is really appreciated.

**Comment by kaspermarstal** [comment] 2018-12-17 14:51
It looks like you are giving transformix a string as the first argument (`newImage=image_dir+filename`) whereas it should be an actual image image. Note that you cannot pass a 3D image to transformix since the transform is a 4D transform. It has to be a 4D image with the same dimensions as the 4D image you gave to elastix.

As for your your questions:

1. `resultImage` already contains your transformed images. If you want to apply the transformation separately, make another 4D image with all your images and give this to transformix.

2. Yes, you should apply the same transformation to the label images. Make a 4D image with the labels (in the same order, and the same number of label images) and give this to transformix. Set "ResampleInterpolator" to "FinalNearestNeighborInterpolator" so that the labels are not interpolated at the borders.

3. You should not apply the same transformation to the follow-up scans. Assuming these images were acquired at another timepoint, they are new images and will not be aligned with the baseline scans, so they need to be registered again.

**Comment by sara-eb** [comment] 2018-12-18 08:11
@kaspermarstal  Thanks a lot for your comments. I am new in registration techniques and beginner in both ANTs and SimpleElastix. I tried few registration techniques in ANTs, however, using SimpleElastix is much easier. Thank you for providing such useful tool. 

I applied the transformation on label files as well with the following commands:

```
# concatenate 3D label files into one 4D file
label_dir='/home/esomayeh/workspace/registration/labels/'
population_label=listdir(label_dir)
vectorOfImages=sitk.VectorOfImage()
for filename in population_label:
    vectorOfImages.push_back(sitk.ReadImage(label_dir+filename))
label4d=sitk.JoinSeries(vectorOfImages)

transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()

# Turn off interpolation for labels (a bug in SWIG wrapping prevents us from writing directly to a parameter map in a vector so we have unwrap it first) 
transformParameterMap = transformParameterMapVector[0]
transformParameterMap["ResampleInterpolator"] = ["FinalNearestNeighborInterpolator"]
resultLabel = sitk.Transformix(label4d, transformParameterMap)
print("Labelransformation done!")
```
Then, I converted the `resultLabel` SimpleITK Image into an array, which I could see the transformed volumes results as 4 dimentional array (and I did the same for `resultImage` of intensity volumes):

```
# convert the result SITK image as array
resultLabelArray=sitk.GetArrayFromImage(resultLabel)
```
My question here is what is the difference between the `resultImage` arrays that we save them and the follwoing transformation, which is being done by ` sitk.Transformix`
```
resultImage = elastixImageFilter.GetResultImage()
transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()
transformedNewImage = sitk.Transformix(image4d, transformParameterMapVector)
```

- **NOTE:** In one of the related paper in my area, authors have used multi-atlas rigid registration, by registering two scans by maximization of **normalized mutual information (NMI)** using **LBFGS** optimization technique. After regiteration, the intensity of theree structures of interests ranged to 0.92, 0.85, and 0.73, which this gives a spatial prior of object to the segmentation algorithm. 

- Authors have also mentioned that they have registered each scan to all training scans (i.e., groupwise registration) , where the optimization was initialized by the translation implied by **the center of mass of the manual segmentations of a specified structure of interest**. 

I wanna do the similar registration on my data to align volumes, How this can be done by `groupwise` registration? Should I add parameters to the `parameterMapVector` as mentioned in [this link](https://discourse.itk.org/t/beginner-registration/929)? For example,
```

parameterMapVector = sitk.VectorOfParameterMap()
parameterMapVector.append(sitk.GetDefaultParameterMap("affine"))
parameterMapVector.append(sitk.GetDefaultParameterMap("bspline"))
elastixImageFilter.SetParameterMap(parameterMapVector)
```

- How can I assign the NMI and LBFGS to the registration process during groupwise registration?

**Comment by kaspermarstal** [comment] 2018-12-19 21:11
```
resultImage = elastixImageFilter.GetResultImage()
transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()
transformedNewImage = sitk.Transformix(image4d, transformParameterMapVector)
```

`resultImage` and `transformedNewImage ` will identical (if image4d is the image you gave to `elastixImageFilter`).


To use NMI, set call `elastixImageFilter.SetParameter("Metric", "AdvancedMattesMutualInformation")`. This is the default though, so you are already using it. You can use `PrintParameterMap` to inspect the contents of the parameter map. Also use use the SetParameter method to also select the LBFGS optimizer. You can see the paramters to use here: http://elastix.isi.uu.nl/doxygen/parameter.html. 

You cannot use the affine and bspline default parameter maps to do groupwise registration because these are setup for 3d registration. Just use the groupwise. There is a groupwise affine transform that you can use to initialize the registration. See the page linked above for the parameters to use (search through with ctrl+f).

**Comment by sara-eb** [comment] 2018-12-23 11:04
@kaspermarstal Thanks for your comments.
Sorry if I am asking so many question, I am not sure if I am doing correctly or not. 
Groupwise registration with default values gave me the following registration (as you can see the overlay of 2 patients in the population):
![overlay-registration](https://user-images.githubusercontent.com/24641528/50291826-9149e000-04aa-11e9-9c27-76c8a19571d3.png)

- It seems it has not fully matched the volumes in thepopulation, Do you have any other suggestion?

According to the transformation that I am trying to apply on my data, the followings are the criteria that has been mentioned:

- Multi-atlas **Rigid** Registration

- **NMI** similarity metric

- optimizer: **LBFGS**
- two stages of Gaussian blurring (I did not add any scales to the `FixedImagePyramid` and `MovingImagePyramid`, and the `NumberOfResolutions` by default is `4`, which I did not change)

-  They have mentioned about euler transform (which only involves translation and rotation with isotropic scaling):  **EulerTransform**

- Translation has been initialized by **the center of mass** (in [this link](http://elastix.isi.uu.nl/doxygen/classitk_1_1CenteredTransformInitializer2.html), there are options for initializing the translation, how to add as a parameter to the transformation?)

I changed the parameters as follows, but I am not sure if it correct or not, 
```
p=sitk.GetDefaultParameterMap('groupwise')
p['Optimizer']=['QuasiNewtonLBFGS']
p['LBFGSUpdateAccuracy']=['5']
p['Transform']=['EulerTransform']
p['Metric']=['AdvancedMattesMutualInformation']
p['AutomaticTransformInitializationMethod']=['CenterOfGravity']
```
After the registration by these parameters, it did not transform the input images. How can I improve the registration?

**Comment by sara-eb** [comment] 2018-12-23 11:49
1. Should I build a template from a few patients and rigidly register all to the template?

**Comment by kaspermarstal** [comment] 2019-01-02 10:04
Yes that is also possible. The use pairwise registration to register the rest of the patients to the template

**Comment by kaspermarstal** [comment] 2019-02-06 13:05
Closing due to lack activity.

**Closed by kaspermarstal** 2019-02-06 13:05 UTC

**Comment by quakberto** [comment] 2019-04-17 23:08
Hi! I'm also interested in the groupwise registration and was wondering whether there is currently an affine transform implemented for the groupwise case?

> You can see the paramters to use here: http://elastix.isi.uu.nl/doxygen/parameter.html.

> You cannot use the affine and bspline default parameter maps to do groupwise registration because these are setup for 3d registration. Just use the groupwise. There is a groupwise affine transform that you can use to initialize the registration. See the page linked above for the parameters to use (search through with ctrl+f).

@kaspermarstal could you point me to the one as I unfortunately don't seem to find it. Thanks a lot!

**Comment by hungyiwu** [comment] 2020-07-19 22:50
> EDIT: Found it! The best is probably to use the AffineLogStackTransform introduced in elastix 4.9 (https://github.com/SuperElastix/elastix/releases). It seems to work fine for me and the log affine parameters can be converted into an affine transformation using scipy.linalg.expm.

@m-albert I tried to use `AffineLogStackTransform` but got this error:
```
itk::ERROR: No default parameter map "AffineLogStackTransform".
```
Have you seen this before? Any thoughts would be appreciated!

**Comment by m-albert** [comment] 2020-07-20 17:00
Hi @hungyiwu, I can't reproduce the problem in my current setup.

How do you set the Transform? From the error it seems you're trying to call a default parameter map called `AffineLogStackTransform`. Instead, for me this code works:

```python
    groupwiseParameterMap2 = sitk.GetDefaultParameterMap('groupwise')
    groupwiseParameterMap2['Transform'] = ['AffineLogStackTransform']
```

Hope that helps!

**Comment by hungyiwu** [comment] 2020-07-20 21:57
@m-albert yeah I thought it's a default parameter, and your code worked! Thank you!!
