### ISSUE TITLE
SuperBuild hangs on cloning elastix repository (OSX)

### ISSUE THREAD

**Issue by khufkens** [SuperElastix/SimpleElastix#66] opened 2017-01-16 09:34 UTC
Seems like the build hangs on cloning the elastix repository. Not sure where I have to look to fix this. Could be a server side issue.

Any pointers are appreciated (and thanks for putting this toolbox together!!!)

**Comment by kaspermarstal** [comment] 2017-01-16 20:00
I have previously had problems building on hospital networks because the git protocol is blocked. You can check ELASTIX_REPOSITORY_URL CMake variable to see if it is git or https. Change to https if necessary. If this doesnt work you can download elastix yourself, compile as a library, and set USE_SYSTEM_ELASTIX CMake variable to ON.

**Comment by khufkens** [comment] 2017-01-16 20:08
Thanks, will try!

**Comment by khufkens** [comment] 2017-01-24 11:15
I added .git to the url at ELASTIX_REPOSITORY_URL, this seems to have fixed it (I think, didn't track the breakpoint but it's still running after a good while). Will keep you posted when it finishes.

**Comment by khufkens** [comment] 2017-01-24 11:51
bailed on a rather indescript:
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2

Will try to build on linux, will probably be a bit more stable...

**Comment by xycyx** [comment] 2017-03-07 03:57
Same issue as @khufkens, did you solve this issue?

`[ 67%] Built target SimpleITKTclsh
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by kaspermarstal** [comment] 2017-03-07 10:18
Can you run it in just a single thread (i.e. no -j4 or similar)? Then it becomes easier to see exactly where it breaks

**Comment by khufkens** [comment] 2017-03-07 20:30
On linux (Ubuntu 14.04) I can't even get past the initial download phase.

With this error. Rather strange as Curl is up to date.
log: Protocol "https" not supported or disabled in libcurl

**Comment by xycyx** [comment] 2017-03-07 23:56
Thank you @kaspermarstal , then I used `make -j1` 
The error information lists below, I worked on Mac OS 10.12.3 using Apple clang-800.0.42.1, Python 2.7.12 :: Anaconda 4.2.0 (x86_64)


[ 34%] Built target SimpleITK_PYTHON
Scanning dependencies of target PythonVirtualEnv
[ 34%] Creating python virtual enviroment...
Already using interpreter /Users/yxcheng/Software/anaconda/bin/python
Not deleting /Users/yxcheng/GitRepos/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin
New python executable in /Users/yxcheng/GitRepos/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python
Installing setuptools, wheel...
  Complete output from command /Users/yxcheng/GitRe...irtualenv/bin/python - setuptools wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/yxcheng/Software/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/yxcheng/Software/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/yxcheng/GitRepos/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/yxcheng/GitRepos/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/yxcheng/GitRepos/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/lib/python2.7/lib-dynload/_io.so
----------------------------------------
...Installing setuptools, wheel...done.
CMake Error at PythonVirtualEnvInstall.cmake:40 (message):
  Creation of Python virtual enviroment failed.

  Traceback (most recent call last):

    File "/Users/yxcheng/GitRepos/build/virtualenv/virtualenv.py", line 2332, in <module>
      main()
    File "/Users/yxcheng/GitRepos/build/virtualenv/virtualenv.py", line 711, in main
      symlink=options.symlink)
    File "/Users/yxcheng/GitRepos/build/virtualenv/virtualenv.py", line 944, in create_environment
      download=download,
    File "/Users/yxcheng/GitRepos/build/virtualenv/virtualenv.py", line 900, in install_wheel
      call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
    File "/Users/yxcheng/GitRepos/build/virtualenv/virtualenv.py", line 795, in call_subprocess
      % (cmd_desc, proc.returncode))

  OSError: Command /Users/yxcheng/GitRe...irtualenv/bin/python - setuptools
  wheel failed with error code 1



make[5]: *** [Testing/Installation/PythonVirtualenv/bin/python] Error 1
make[5]: *** Deleting file `Testing/Installation/PythonVirtualenv/bin/python'
make[4]: *** [Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2

**Comment by kaspermarstal** [comment] 2017-03-08 15:01
Try to type `hash -r python` as outlined [in this stackoverflow thread](http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder). Otherwise try googling the error. This like an issue related to your local python configuration and it is difficult for me to debug from afar I am afraid.

**Comment by kaspermarstal** [comment] 2017-03-10 07:55
Another user just reported that he had the same problem, that it was caused by anaconda, and when using the default python installation everything installed smoothly

**Comment by kaspermarstal** [comment] 2017-10-29 16:15
Closing. This has been fixed. 

Feel free to reopen you run into this issue again.

**Closed by kaspermarstal** 2017-10-29 16:15 UTC
