### ISSUE TITLE
 Protocol "https" not supported or disabled in libcurl 

### ISSUE THREAD

**Issue by engineeringmath** [SuperElastix/SimpleElastix#75] opened 2017-02-23 20:47 UTC
Hello Guys,
Sorry if this error does not belong here.  I am trying to install SimpleElastix with superbuild and I get the following error.   I searched for a solution and tried some of the things that had been suggested but the problem continues. I have little familiarity with Linux.
Any help?

-- downloading...
       src='https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=6e0cc6d1bdac7a4308151f9b3571b86e&name=pcre-8.37.tar.gz'
       dst='/home/davood/build/PCRE-prefix/src/method=midas.bitstream.download&checksum=6e0cc6d1bdac7a4308151f9b3571b86e&name=pcre-8.37.tar.gz'
       timeout='none'
error: downloading 'https://www.lua.org/ftp/lua-5.1.5.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---error: downloading 'https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=2d6ec8ccdf5c46b05ba54a9fd1d130d7&name=swig-1.7.0.zip' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---error: downloading 'https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=6e0cc6d1bdac7a4308151f9b3571b86e&name=pcre-8.37.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---

**Comment by kaspermarstal** [comment] 2017-02-23 21:32
Can you check if it is a network issue? Is it reproduced if you try to install on a different (e.g. home) network?

**Comment by engineeringmath** [comment] 2017-02-23 21:37
Thank you so much for the quick reply.
Unfortunately I don't think I can try it on another network.   This is a desktop computer in our lab and it's the only computer I have access to right now.

**Comment by kaspermarstal** [comment] 2017-10-29 16:17
Closing since it has been long since I last run into this issue.

**Closed by kaspermarstal** 2017-10-29 16:17 UTC
